WeekFood/WeekFood

db/WeekFood.sql
src/app/controllers/ApiController.php
src/app/controllers/CarruselController.php
src/app/controllers/MenuController.php
src/app/controllers/PrincipalController.php
src/app/models/ApiModel.php
src/app/models/CarruselModel.php
src/app/models/MenuModel.php
src/app/views/api.php
src/configs/routes.php
src/core/MVC/Controller.php
src/core/MVC/Model.php
src/core/MVC/Router.php
src/test.html

API para peticiones iniciada con menu y carrusel.
Devuelve JSON segun la base de datos.

feat(#22): API para peticiones.

---

src/app/views/cliente/scss/estilo.scss

fix(#31): [SCSS] En estilo.scss no puede importar pages/principal

---

build/build.sh
src/app/views/index.php

feat(#38): Carpeta con scripts JS y carpeta libs

---

src/app/views/cliente/scss/abstracts/_colores.scss
src/app/views/cliente/scss/components/_cabecera.scss
src/app/views/cliente/scss/components/_carrusel.scss
src/app/views/cliente/scss/components/_principal.scss
src/app/views/cliente/scss/layout/_distribucion.scss

Issue #74 
Esto es el estilo que hay en la rama t_pruebas, afectando solo a la página principal.

Actualizacion SCSS de t_pruebas

---

src/app/controllers/ApiController.php
src/app/controllers/CarruselController.php
src/app/controllers/MenuController.php
src/app/controllers/ProductosController.php
src/core/MVC/Controller.php

Issue #65.
El controller detectará si una petición es para la api en base a la url de la petición, de ser así automáticamente pondrá el header json utf8.

feat(#65) : Prevencion de repeticion de header(xxx) moviendolo a controller.

---

build/build.sh
build/minimizarCSS.js
build/minimizarJS.js
package-lock.json
package.json
src/app/views/index.php

Closes #81 
__Css :__ ~~Se construye *estilo.css* normal, y se reemplaza con la versión mini.~~ Node-sass lo hace de forma nativa.
__Js :__ Ya no se copian los archivos, se compilan desde src a dist ~~en versión temp_, y se vuelven a juntar los temp_ (y se borran)~~ en uno llamado *WeekFood.js*, el cual contiene todos los archivos js. 
__Nuevos script :__ *npm run miniJS miniCSS*, minifican sus respectivos mediante la descripción anterior, *npm run mini* ejecuta ambos.
__Html  :__  ya se ha preparado el html para incluir WeekFood.js en vez de main y vistas.
Edit JS :  Commit dc2b338f1b644d5aef9d74fc3603d33a8b4011c0
Edit CSS : Commit 444615b0dc5748e0879bb97e4a138316fec87ee2

feat(#81) : Minificación automatizada de JS y CSS en post-construcción.

---

src/app/views/cliente/js/main.js
src/app/views/cliente/scss/components/_cabecera.scss
src/app/views/cliente/scss/components/_menu.scss
src/app/views/cliente/scss/layout/_distribucion.scss
src/app/views/index.php

Añadida animación de despliegue del menú en móvil, tanto el panel como los items en el menú.

feat(#90) : Animacion despliegue menu movil.

---

src/app/views/cliente/js/funciones.js

rm(#101) : Feat de la pantalla de carga eliminado.

---

src/cliente/index.html
src/cliente/scss/abstracts/_colores.scss
src/cliente/scss/components/_boton.scss
src/cliente/scss/estilo.scss

Closes #119 
---
Para probarlos:
```js
$(`
<div class="c-boton">Cerrar</div>
<div class="c-boton c-boton--exito">Confirmar pago</div>
<div class="c-boton c-boton--peligro">Borrar cuenta</div>
<div class="c-boton c-boton--advertencia">Vaciar carrito</div>
<div class="c-boton c-boton--basico">Cambiar avatar</div>
`
).insertAfter($('.c-principal__texto'));
```

feat(#119): [SCSS] Crear componente boton

---

src/cliente/js/componentes/ventanaModal.js

fix(#122) : Rename de botones, prevencion de cerrar la ventana al clickar en contenido.

---

package-lock.json
src/cliente/js/abstractos.js
src/cliente/js/componentes/carrusel.js
src/cliente/js/funciones.js
src/cliente/js/vistas/productos.js

Issue : #127 
**Sistema para cacheo de JSONs.**
Se piden los datos con `GLOBAL_CACHE_JSONS.getJSON(url)`, retorna un promise que se resolverá con el contenido devuelto por la API.
- **Si 'url' no esta en cache**, se pide, se cachea, se registra el epoch y se retorna el contenido de la API.
- **Si 'url' esta en cache**:
- Si hace **menos de 25 segundos**, se retorna el contenido de la API.
- **De lo contrario**, se borra y se vuelve a descargar, registrar y retorna.
**DISCLAIMER:
CUANDO TESTEEIS, TENED EN CUENTA QUE  LAS PETICIONES SON ASINCRONAS, SI SE HACEN VARIAS A LA VEZ, NO DA TIEMPO A CACHEAR, EL SISTEMA RESPONDERÁ BIEN, PERO SI QUE SE VAN A HACER TODAS LAS PETICIONES A LA API.**

feat(#127) : Gestion de JSONs en cache.

---

db/WeekFood.sql

- Añadido el campo precio en la tabla productos
- Añadido precios y descripciones(datos) en la tabla productos
- Id autoincremental de la tabla productos actualizado.

feat(#132) Modificar BD

---

package-lock.json
src/cliente/scss/components/_productos.scss

- Modificado el ancho del producto a 200px.

fix(#143) Arreglado ancho producto

---

src/cliente/js/vistas/principales.js
src/cliente/js/vistas/productos.js
src/cliente/scss/components/_final.scss
src/cliente/scss/estilo.scss

Issue  #151 
c-final es el final de la propia web, para invocarlo cuando nos quedamos sin contenido y que el apartado principal se quede vacío.
- Se ha creado el estilo de final.
- Se ha actualizado los filtros de productos para que no invoquen a c-principal sino a c-final.
- Se ha actualizado la vista error para el mismo propósito.

feat(#151) : Componente final.

---

src/cliente/js/vistas/productos.js
src/cliente/scss/components/_producto.scss
src/cliente/scss/components/_productos.scss

- Eliminado div titulo-container, que provocaba que no cogiera bien el grid del producto el propio título.

fix(#150) Arreglar titulo

---

src/cliente/js/componentes/carrito.js
src/cliente/js/vistas/productos.js

fix(#158) : Reemplazado event.currentTarget por this, para facilitar la comprension del codigo.

---

src/cliente/js/core/carrito/Carrito.js

Fixes #152 
El método es el que tiene el check de cantidad máxima, por lo que ya no puede superar 99, como lo haría si se incrementase a través de Articulo

fix(#152): [Carrito] incrementar cantidad a traves del método propio

---

src/cliente/js/componentes/carrito.js

Fixes #186 
Siento el inconveniente

fix(#186): Quitado código sobrante en carrito.js post PR #148

---

src/cliente/index.html
src/cliente/js/componentes/carrito.js
src/cliente/scss/components/_cabecera.scss
src/cliente/scss/components/_carrito.scss

Issue #183 
- ~El icono de la campana se queda a la izq gracias al flex.~
- ~El icono del carro cambia dinamicamente cuando aparece el de la campana.~
- El boton de pagar tiene tamaño minimo para 5 caracteres, impidiendo que se reescale. ( XXX.X€ )
- Aprovechado para ordenar un if con varias condiciones que era horrible para leer.
- Reemplazado campana por un circulo que salta ~cada 2.4s durante 0.6s~ al cabo de 1.2s

 fix(#183) : Campana reemplazada y boton pagar perfeccionado, legibilidad del codigo mejorada.

---

src/cliente/scss/components/_ventana-modal.scss

fix(#179) : Puesto el titulo y la equis por encima del contenido, y el contenido no tapa los botones.

---

src/cliente/js/componentes/carrito.js

Issue #207 
Añadida la condición para comprobar, tanto si esta iniciado como si esta plegado a la hora de forzar su despliegue al añadir el 1º articulo.

fix(#207) : El carrito ya no se pliega cuando no debe.

---

src/cliente/js/core/Gestion Productos/GestorProductos.js
src/cliente/scss/components/_modal-producto.scss

Fixes #209 
- Cambiado tamaño del modal a "pequeño", que tras el PR mide lo que media "medio" antes
- Añadido media query para la altura de la imagen en +1440px

fix(#209): [Modal Producto] Revisar tamaño y layout post #192

---

src/cliente/js/core/carrito/Articulo.js
src/cliente/js/core/carrito/Carrito.js

Issue #188 
Si se vuelve a hacer click en "añadir al carrito" de un articulo que ya se había añadido, se moverá al final del carrito.

feat(#188) : Poner el articulo actualizado al final del carrito.

---

src/cliente/js/init.js
src/cliente/scss/components/_menu.scss

Issue #215 
La animación dura unos decasegundos mas, pero añade un rebote, tanto al desplegar como al plegar el 
menú.
Los items del menú también rebotan al salir.

feat(#215) : Animación del menú en móvil mejorada.

---

src/cliente/js/vistas/productos.js
src/cliente/scss/components/_producto.scss

feat(#181): [Grid Productos] Permitir abrir modal clickando en cualquier parte

---

src/cliente/js/componentes/ventanaModal.js

feat(#224) : Añadido boton info opcional al tipo info, añadido jsdoc

---

src/cliente/js/vistas/principales.js
src/cliente/scss/components/_principal.scss

Closes #233
El único cambio minimamente controversial es el salto de línea extra

feat(#233): [c-principal] Mejora visual del párrafo

---

src/cliente/js/componentes/carrito.js
src/cliente/scss/components/_carrito.scss

feat(#236): [c-carrito] Mejoras visuales

---

src/app/resources/CarritosResource.php

Issue #240 
Carrito ahora es funcional con la autenticación de API

feat(#240) : Adaptar carrito a auth

---

src/cliente/js/componentes/acceso.js
src/cliente/js/funciones.js

fix(#241) : Carga del perfil despues de descargar los datos del usuario.

---

db/WeekFood_creacion.sql
db/WeekFood_datos.sql

Issue #247 
Eliminado WeekFood.sql para ser reemplazado por WeekFood_creacion.sql y WeekFood_datos.sql
Se han creado las tablas:
- nivelesprivilegio
- ubicaciones
- metodospago
- tiposmetodospago
- pedidos
Se ha ampliado el usuario con las columnas:
- telefono
- nacimiento
- nivelprivilegio

feat(#247) : BD actualizada para CRUD y datos del usuario

---

src/cliente/scss/abstracts/_colores.scss
src/cliente/scss/components/_boton.scss

Issue  #256
Se ha usado el color `ASBESTOS`
> https://flatuicolors.com/palette/defo

 feat(#256) : Boton deshabilitado

---

admin/src/app/app-routing.module.ts
admin/src/app/app.module.ts
admin/src/app/modal-categoria/modal-categoria.component.html
admin/src/app/modal-categoria/modal-categoria.component.ts
admin/src/app/models/Categoria.ts
admin/src/app/services/categorias.service.ts
admin/src/app/views/categorias/categorias.component.html
admin/src/app/views/categorias/categorias.component.scss
admin/src/app/views/categorias/categorias.component.ts
src/app/resources/ProductosResource.php
src/configs/routes.php

Closes #265 
Se ha decidido que no se va a poder borrar una Categoría. Básicamente porque tal como esta ahora lo de que un producto tiene subcategorías que formaban parte de la categoría principal borrada, guardadas como simple string, complicaría el código.

feat(#265): [CRUD] [PHP, JS] View, servicio & endpoints Categorias

---

admin/src/app/app-routing.module.ts
admin/src/app/app.module.ts
admin/src/app/modal-carrito/modal-carrito.component.html
admin/src/app/modal-carrito/modal-carrito.component.scss
admin/src/app/modal-carrito/modal-carrito.component.ts
admin/src/app/modal-categoria/modal-categoria.component.html
admin/src/app/modal-categoria/modal-categoria.component.ts
admin/src/app/modal-subcategoria/modal-subcategoria.component.html
admin/src/app/modal-subcategoria/modal-subcategoria.component.ts
admin/src/app/models/Carrito.ts
admin/src/app/services/carritos.service.ts
admin/src/app/views/carritos/carritos.component.html
admin/src/app/views/carritos/carritos.component.scss
admin/src/app/views/carritos/carritos.component.ts
admin/src/styles.scss
src/app/resources/CarritosResource.php
src/app/resources/ProductosResource.php
src/configs/routes.php

Closes #282 
- La fecha se modeliza como String porque como Date da muchos problemas de zonas horarias. 
- El idUsuario y la fecha son validados con la API nativa
- He aprovechado para validar el CRUD Categorias y Subcategorias
- He tenido que reutilizar el método `postCarritoAction` del Resource ya que tenia "pillada" la ruta REST. Lo que pasa es que hacía cosas enfocadas a cliente, es decir que un carrito se traía sus artículos. He tenido que meter varios flags para que haga solo lo que necesita el CRUD (basicamente ignorar articulos y el id de usuario basado en login). _El diff se ha vuelto un poco loco, no he borrado nada, solo wrappeado código en ifs_.

feat(#282): [CRUD] [PHP, JS] View, servicio & endpoints Carritos

---

admin/src/app/app.component.html
admin/src/app/app.component.ts
admin/src/app/views/login/login.component.html
admin/src/app/views/login/login.component.ts

fix(#289) : Errores de despliegue

---

admin/src/app/app-routing.module.ts
admin/src/app/app.component.ts
admin/src/app/app.module.ts
admin/src/app/cabecera/cabecera.component.scss
admin/src/app/modal-carrito/modal-carrito.component.ts
admin/src/app/modal-producto/modal-producto.component.ts
admin/src/app/services/productos.service.ts
admin/src/app/sidebar/sidebar.component.scss
admin/src/app/views/productos/productos.component.ts

feat(#275) : Imports absolutos

---

admin/src/app/app-routing.module.ts
admin/src/app/app.component.ts
admin/src/app/app.module.ts
admin/src/app/cabecera/cabecera.component.scss
admin/src/app/modal-carrito/modal-carrito.component.ts
admin/src/app/modal-producto/modal-producto.component.ts
admin/src/app/services/productos.service.ts
admin/src/app/sidebar/sidebar.component.scss
admin/src/app/views/productos/productos.component.ts

Revert "feat(#275) : Imports absolutos"

---

admin/src/app/app-routing.module.ts
admin/src/app/app.component.ts
admin/src/app/app.module.ts
admin/src/app/cabecera/cabecera.component.scss
admin/src/app/modal-carrito/modal-carrito.component.ts
admin/src/app/modal-producto/modal-producto.component.ts
admin/src/app/services/productos.service.ts
admin/src/app/sidebar/sidebar.component.scss
admin/src/app/views/productos/productos.component.ts

feat(#276) : Imports estáticos.

---

admin/src/app/app-routing.module.ts
admin/src/app/app.module.ts
admin/src/app/modal-usuario/modal-usuario.component.html
admin/src/app/modal-usuario/modal-usuario.component.scss
admin/src/app/modal-usuario/modal-usuario.component.ts
admin/src/app/models/Usuario.ts
admin/src/app/services/usuarios.service.ts
admin/src/app/views/usuarios/usuarios.component.html
admin/src/app/views/usuarios/usuarios.component.scss
admin/src/app/views/usuarios/usuarios.component.ts
src/app/resources/UsuariosResource.php
src/configs/config.php
src/configs/preprod_config.php
src/configs/prod_config.php
src/configs/routes.php

Issue #284 
Creada vista crud usuarios, modal usuario.
Permite crear, ver, modificar y borrar usuarios.
Se ha añadido la funcionalidad de modificar contraseñas (aleatoriamente), y ver/borrar fotos de perfil.

feat(#284) Crud usuarios

---

build/despl-local.sh
build/despl-preprod.sh
build/despl-prod.sh

Issue #295 
Como para desplegar tanto en local como en producción somos root, los permisos de los directorios y archivos son root:root 755, y no podemos crear nuevos archivos.

feat(#295) : Permisos de directorio para www-data

---

admin/src/app/modal-producto/modal-producto.component.html
admin/src/app/modal-producto/modal-producto.component.scss
admin/src/app/views/productos/productos.component.html
admin/src/app/views/productos/productos.component.scss

fix(#288): [CRUD] Imágenes view Productos

---

admin/src/app/app-routing.module.ts

fix(#SN) : AuthGuard faltantes.

---

admin/src/app/services/productos.service.ts

fix(#300): [CRUD] No se parsea bien el boolean de destacado
